"""empty message

Revision ID: 27e11e689077
Revises: 7778b8389280
Create Date: 2019-09-02 18:18:46.052954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e11e689077'
down_revision = '7778b8389280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('website', sa.String(), nullable=True))
    op.add_column('datasets', sa.Column('reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'reference')
    op.drop_column('colleges', 'website')
    # ### end Alembic commands ###
