"""empty message

Revision ID: 9a7434a283f9
Revises: 4f0c0b77c248
Create Date: 2019-08-27 20:34:38.236470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7434a283f9'
down_revision = '4f0c0b77c248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'year')
    # ### end Alembic commands ###
