"""empty message

Revision ID: a2be7d7f9ee4
Revises: fa6c20d97f11
Create Date: 2019-08-22 10:17:43.846401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2be7d7f9ee4'
down_revision = 'fa6c20d97f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('college_type', sa.String(), nullable=True),
    sa.Column('college_ownership', sa.String(), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colleges')
    # ### end Alembic commands ###
