"""empty message

Revision ID: d7df587ba4e3
Revises: a2be7d7f9ee4
Create Date: 2019-08-22 13:55:41.000354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7df587ba4e3'
down_revision = 'a2be7d7f9ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('xPosition', sa.Integer(), nullable=True))
    op.add_column('colleges', sa.Column('yPosition', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colleges', 'yPosition')
    op.drop_column('colleges', 'xPosition')
    # ### end Alembic commands ###
